Read 2 sets A and B with cardinality m & n. Then apply operations on A and B as:
a) union  
b) intersection  
c) difference
d) symmetric difference
e) subset
f) complement
g) Using these go for the De morgan's laws
h) cartesian product &
i) count the number of bijective maps
j) number of onto maps
j) all subsets of a set i.e. power set

In [23]:
def cartesian_product(A, B):
    prod = set()
    
    for a in A:
        for b in B:
            prod.add((a, b))
            
    print(f"A X B: {prod}")
   

def fact(n):
    if n <= 1:
        return 1
    return n * fact(n - 1)

    
def bijective_maps(A, B):
    if len(A) == len(B):
        n = len(A)
        print(f"Number of bijective maps: {fact(n)}")
    else:
        print(f"Bijective maps not possible!")
    return

     
def C(n, r):
    return fact(n) / (fact(r) * fact(n - r))
              

def onto_maps(A, B):
    m = len(A)
    n = len(B)
    
    if m < n:
        return 0
              
    else:
        sum = 0
        for k in range(n + 1):
            sum += (-1 ** k) * C(n,k) * ((n - k) ** m)
        
        return int((n ** m) - sum)

              
def subsets(A, sub = set(), element = [], i = 0):
    if i == len(A):
        sub.add(tuple(element))
        return sub
    
    subsets(A, sub, element, i + 1)
    subsets(A, sub, element + [A[i]], i + 1) 
    return sub
    

m = int(input("Cardinality of set 1: "))
n = int(input("Cardinality of set 2: "))

print(f"Input {m} elements into set A: ")
elements = map(int, input().split())

A = set(elements)

print(f"Input {n} elements into set B: ")
elements = map(int, input().split())

B = set(elements)

U = A | B #universal set
A1 = U - A #A's complement
B1 = U - B #B's complement

print(f"A: {A}")
print(f"B: {B}")
print(f"U: {U}")

print(f"Union: {U}")

print(f"Intersection: {A & B}")

print(f"Difference: {A - B}")

print(f"Symmetric Difference: {A ^ B}")

if A.issubset(B):
    print(f"A is a subset of B")
elif B.issubset(A):
    print(f"B is a subset of A")
else:
    print("No subsets found!")
    
print(f"Complement of A: {U - A}")
print(f"Complement of B: {U - B}")

print(f"(A U B)' = A' intersect B': {A1 & B1}")
print(f"(A intersect B)' = A'U B': {A1 | B1}")

cartesian_product(A, B)
cartesian_product(B, A)
              
bijective_maps(A, B)
print(f"Number of onto maps: {onto_maps(A, B)}")

print(f"Subsets of A: {subsets(list(A))}")
print(f"Subsets of B: {subsets(list(B))}")

print(A)
print(B)

Cardinality of set 1: 3
Cardinality of set 2: 2
Input 3 elements into set A: 
1 2 3
Input 2 elements into set B: 
3 4
A: {1, 2, 3}
B: {3, 4}
U: {1, 2, 3, 4}
Union: {1, 2, 3, 4}
Intersection: {3}
Difference: {1, 2}
Symmetric Difference: {1, 2, 4}
No subsets found!
Complement of A: {4}
Complement of B: {1, 2}
(A U B)' = A' intersect B': set()
(A intersect B)' = A'U B': {1, 2, 4}
A X B: {(2, 4), (3, 4), (1, 4), (2, 3), (3, 3), (1, 3)}
A X B: {(4, 3), (3, 1), (4, 2), (3, 3), (3, 2), (4, 1)}
Bijective maps not possible!
Number of onto maps: 18
Subsets of A: {(1, 3), (2,), (1, 2), (1, 2, 3), (2, 3), (1,), (), (3,)}
Subsets of B: {(1, 3), (2,), (1, 2), (3, 4), (1, 2, 3), (4,), (2, 3), (1,), (), (3,)}
{1, 2, 3}
{3, 4}


In [16]:
def subsets(A, sub = [], i = 0):
    if i == len(A):
        print(sub, end = ' ')
        return
    
    subsets(A, sub, i + 1)
    subsets(A, sub + [A[i]], i + 1) 

subsets([1, 2, 3])

[] [3] [2] [2, 3] [1] [1, 3] [1, 2] [1, 2, 3] 

In [30]:
def subsets(A, sub = set(), element = list(), i = 0):
    if i == len(A):
        sub.add(tuple(element))
        return sub
    
    subsets(A, sub, element, i + 1)
    subsets(A, sub, element + [A[i]], i + 1) 
    return sub

sub = set()
print(subsets([1, 2, 3]), sub, [])
sub = set()
print(subsets([3, 4]), sub, [])

{(1, 3), (2,), (1, 2), (1, 2, 3), (2, 3), (1,), (), (3,)} set() []
{(1, 3), (2,), (1, 2), (3, 4), (1, 2, 3), (4,), (2, 3), (1,), (), (3,)} set() []


uisng numpy do the following:
a) add, subtract, multiply and divide 2 matrices
b) find the determinant of matrices
c) check if the matrcies are symmetric or not
d) check if the matrcies are skew-symmetric or not
e) check if the matrcies are Hermitian or not
f) check if the matrcies are skew Hermitian or not
g) check if the matrcies are orthogonal or not
h) check if the matrices are upper or lower triangular or not
i) adjoint of the matrices

In [46]:
import numpy as np

# Define a function to print matrices nicely
def print_matrix(mat, name):
    print(f"{name}:\n{np.array2string(mat, separator=' ', suppress_small=True)}\n")
    
    
A = np.matrix([[2, 3],
               [3, 2]])

B = np.matrix([[4, 1],
               [1, 4]])

print(f"A:")
print(A)

print(f"B:")
print(B)

print(f"A + B:")
print(A + B)

print(f"A - B:")
print(A - B)

print(f"A x B:")
print(A * B)

print(f"A / B:")
print(A // B)

AT = A.transpose()
BT = B.transpose()
print("Transpose of A:")
print(AT)
print("Transpose of B:")
print(BT)
    
def check_symm(A):
    AT = A.transpose()
    if A.array_equal(AT):
        print(f"{A} is symmetric")
    else:
        print(f"{A} is not symmetric")
        
check_symm(A)
    
    

A:
[[2 3]
 [3 2]]
B:
[[4 1]
 [1 4]]
A + B:
[[6 4]
 [4 6]]
A - B:
[[-2  2]
 [ 2 -2]]
A x B:
[[11 14]
 [14 11]]
A / B:
[[0 3]
 [3 0]]
Transpose of A:
[[2 3]
 [3 2]]
Transpose of B:
[[4 1]
 [1 4]]


AttributeError: 'matrix' object has no attribute 'array_equal'