Read 2 sets A and B with cardinality m & n. Then apply operations on A and B as:
a) union  
b) intersection  
c) difference
d) symmetric difference
e) subset
f) complement
g) Using these go for the De morgan's laws
h) cartesian product &
i) count the number of bijective maps
j) number of onto maps
j) all subsets of a set i.e. power set

In [23]:
def cartesian_product(A, B):
    prod = set()
    
    for a in A:
        for b in B:
            prod.add((a, b))
            
    print(f"A X B: {prod}")
   

def fact(n):
    if n <= 1:
        return 1
    return n * fact(n - 1)

    
def bijective_maps(A, B):
    if len(A) == len(B):
        n = len(A)
        print(f"Number of bijective maps: {fact(n)}")
    else:
        print(f"Bijective maps not possible!")
    return

     
def C(n, r):
    return fact(n) / (fact(r) * fact(n - r))
              

def onto_maps(A, B):
    m = len(A)
    n = len(B)
    
    if m < n:
        return 0
              
    else:
        sum = 0
        for k in range(n + 1):
            sum += (-1 ** k) * C(n,k) * ((n - k) ** m)
        
        return int((n ** m) - sum)

              
def subsets(A, sub = set(), element = [], i = 0):
    if i == len(A):
        sub.add(tuple(element))
        return sub
    
    subsets(A, sub, element, i + 1)
    subsets(A, sub, element + [A[i]], i + 1) 
    return sub
    

m = int(input("Cardinality of set 1: "))
n = int(input("Cardinality of set 2: "))

print(f"Input {m} elements into set A: ")
elements = map(int, input().split())

A = set(elements)

print(f"Input {n} elements into set B: ")
elements = map(int, input().split())

B = set(elements)

U = A | B #universal set
A1 = U - A #A's complement
B1 = U - B #B's complement

print(f"A: {A}")
print(f"B: {B}")
print(f"U: {U}")

print(f"Union: {U}")

print(f"Intersection: {A & B}")

print(f"Difference: {A - B}")

print(f"Symmetric Difference: {A ^ B}")

if A.issubset(B):
    print(f"A is a subset of B")
elif B.issubset(A):
    print(f"B is a subset of A")
else:
    print("No subsets found!")
    
print(f"Complement of A: {U - A}")
print(f"Complement of B: {U - B}")

print(f"(A U B)' = A' intersect B': {A1 & B1}")
print(f"(A intersect B)' = A'U B': {A1 | B1}")

cartesian_product(A, B)
cartesian_product(B, A)
              
bijective_maps(A, B)
print(f"Number of onto maps: {onto_maps(A, B)}")

print(f"Subsets of A: {subsets(list(A))}")
print(f"Subsets of B: {subsets(list(B))}")

print(A)
print(B)

Cardinality of set 1: 3
Cardinality of set 2: 2
Input 3 elements into set A: 
1 2 3
Input 2 elements into set B: 
3 4
A: {1, 2, 3}
B: {3, 4}
U: {1, 2, 3, 4}
Union: {1, 2, 3, 4}
Intersection: {3}
Difference: {1, 2}
Symmetric Difference: {1, 2, 4}
No subsets found!
Complement of A: {4}
Complement of B: {1, 2}
(A U B)' = A' intersect B': set()
(A intersect B)' = A'U B': {1, 2, 4}
A X B: {(2, 4), (3, 4), (1, 4), (2, 3), (3, 3), (1, 3)}
A X B: {(4, 3), (3, 1), (4, 2), (3, 3), (3, 2), (4, 1)}
Bijective maps not possible!
Number of onto maps: 18
Subsets of A: {(1, 3), (2,), (1, 2), (1, 2, 3), (2, 3), (1,), (), (3,)}
Subsets of B: {(1, 3), (2,), (1, 2), (3, 4), (1, 2, 3), (4,), (2, 3), (1,), (), (3,)}
{1, 2, 3}
{3, 4}


In [16]:
def subsets(A, sub = [], i = 0):
    if i == len(A):
        print(sub, end = ' ')
        return
    
    subsets(A, sub, i + 1)
    subsets(A, sub + [A[i]], i + 1) 

subsets([1, 2, 3])

[] [3] [2] [2, 3] [1] [1, 3] [1, 2] [1, 2, 3] 

In [30]:
def subsets(A, sub = set(), element = list(), i = 0):
    if i == len(A):
        sub.add(tuple(element))
        return sub
    
    subsets(A, sub, element, i + 1)
    subsets(A, sub, element + [A[i]], i + 1) 
    return sub

sub = set()
print(subsets([1, 2, 3]), sub, [])
sub = set()
print(subsets([3, 4]), sub, [])

{(1, 3), (2,), (1, 2), (1, 2, 3), (2, 3), (1,), (), (3,)} set() []
{(1, 3), (2,), (1, 2), (3, 4), (1, 2, 3), (4,), (2, 3), (1,), (), (3,)} set() []


uisng numpy do the following:
a) add, subtract, multiply and divide 2 matrices
b) find the determinant of matrices
c) check if the matrcies are symmetric or not
d) check if the matrcies are skew-symmetric or not
e) check if the matrcies are Hermitian or not
f) check if the matrcies are skew Hermitian or not
g) check if the matrcies are orthogonal or not
h) check if the matrices are upper or lower triangular or not
i) adjoint of the matrices

In [26]:
import numpy as np

# Define a function to print matrices nicely
def print_matrix(mat, name):
    print(f"{name}:\n{np.array2string(mat, separator=' ', suppress_small=True)}\n")
    
    
# A = np.array([[2, 3],
#                [3, 2]])

# B = np.array([[4, 1],
#                [1, 4]])

A = np.array([[4, 0, 0],
              [2, 5, 0],
              [1, 3, 6]])

B = np.array([[4, 1, 2],
              [0, 4, 1],
              [0, 0, 3]])

print(f"A:")
print(A)
print()

print(f"B:")
print(B)
print()

# addition
print(f"A + B:")
print(A + B)
print()

# subtraction
print(f"A - B:")
print(A - B)
print()

# multiplication
print(f"A x B:")
print(A * B)
print()

AT = A.transpose()
BT = B.transpose()
print("Transpose of A:")
print(AT)
print()
print("Transpose of B:")
print(BT)
print()
    
def check_symm(A):
    if np.array_equal(A, AT):
        print(f"{A} is symmetric")
    else:
        print(f"{A} is not symmetric")
    print()
    
def calc_det(A):
    det_A = np.round(np.linalg.det(A))
    print(f"Det. of \n{A}:")
    print(det_A)
    print()
    
def check_anti_symm(A):
    if np.array_equal(-A, AT):
        print(f"{A} is skew-symmetric")
    else:
        print(f"{A} is not skew-symmetric")
    print()
    
def check_hermitian(A):
    conj_A = np.conj(AT)
    if np.array_equal(A, conj_A):
        print(f"{A} is Hermitian")
    else:
        print(f"{A} is not Hermitian")
    print()
    
def check_skew_hermitian(A):
    conj_A = np.conj(AT)
    if np.array_equal(-A, conj_A):
        print(f"{A} is skew-Hermitian")
    else:
        print(f"{A} is not skew-Hermitian")
    print()
    
def check_orthogonal(A):
    if np.allclose(np.dot(A.T, A), np.eye(A.shape[0])):
        print(f"{A} is orthogonal")
    else:
        print(f"{A} is not orthogonal")
    print()
    
def check_up_tri(A):
    if np.all(np.tril(A, -1) == 0):
        print(f"{A} is upper triangular matrix")
    else:
        print(f"{A} is not upper triangular matrix")
    print()
    
def check_low_tri(A):
    if np.all(np.triu(A, 1) == 0):
        print(f"{A} is lower triangular matrix")
    else:
        print(f"{A} is not lower triangular matrix")
    print()
    
# Function to calculate the cofactor matrix of a 3x3 matrix
def cofactor_matrix(A):
    cofactor_mat = np.zeros_like(A)
    
    # Calculate the cofactor for each element in the matrix
    for i in range(3):
        for j in range(3):
            # Get the minor matrix by excluding row i and column j
            minor = np.delete(np.delete(A, i, axis=0), j, axis=1)
            
            # Calculate the determinant of the minor matrix
            minor_det = np.linalg.det(minor)
            
            # Apply the sign change based on the position (i,j)
            cofactor_mat[i, j] = ((-1) ** (i + j)) * minor_det
    
    return cofactor_mat

# Function to calculate the adjoint (adjugate) of a 3x3 matrix
def adjoint(A):
    cofactor_mat = cofactor_matrix(A)
    # Transpose the cofactor matrix to get the adjoint
    adj_A = np.transpose(cofactor_mat)
    print(f"adjoint of {A}:")
    print(adj_A)
    print()
    

check_symm(A)
check_symm(B)
    
calc_det(A)
calc_det(B)

check_anti_symm(A)
check_anti_symm(B)

check_hermitian(A)
check_hermitian(B)

check_skew_hermitian(A)
check_skew_hermitian(B)

check_orthogonal(A)
check_orthogonal(B)

check_up_tri(A)
check_up_tri(B)

check_low_tri(A)
check_low_tri(B)

adjoint(A)
adjoint(B)

A:
[[4 0 0]
 [2 5 0]
 [1 3 6]]

B:
[[4 1 2]
 [0 4 1]
 [0 0 3]]

A + B:
[[8 1 2]
 [2 9 1]
 [1 3 9]]

A - B:
[[ 0 -1 -2]
 [ 2  1 -1]
 [ 1  3  3]]

A x B:
[[16  0  0]
 [ 0 20  0]
 [ 0  0 18]]

Transpose of A:
[[4 2 1]
 [0 5 3]
 [0 0 6]]

Transpose of B:
[[4 0 0]
 [1 4 0]
 [2 1 3]]

[[4 0 0]
 [2 5 0]
 [1 3 6]] is not symmetric

[[4 1 2]
 [0 4 1]
 [0 0 3]] is not symmetric

Det. of 
[[4 0 0]
 [2 5 0]
 [1 3 6]]:
120.0

Det. of 
[[4 1 2]
 [0 4 1]
 [0 0 3]]:
48.0

[[4 0 0]
 [2 5 0]
 [1 3 6]] is not skew-symmetric

[[4 1 2]
 [0 4 1]
 [0 0 3]] is not skew-symmetric

[[4 0 0]
 [2 5 0]
 [1 3 6]] is not Hermitian

[[4 1 2]
 [0 4 1]
 [0 0 3]] is not Hermitian

[[4 0 0]
 [2 5 0]
 [1 3 6]] is not skew-Hermitian

[[4 1 2]
 [0 4 1]
 [0 0 3]] is not skew-Hermitian

[[4 0 0]
 [2 5 0]
 [1 3 6]] is not orthogonal

[[4 1 2]
 [0 4 1]
 [0 0 3]] is not orthogonal

[[4 0 0]
 [2 5 0]
 [1 3 6]] is not upper triangular matrix

[[4 1 2]
 [0 4 1]
 [0 0 3]] is upper triangular matrix

[[4 0 0]
 [2 5 0]
 [1 3 6]] is lo